### ISSUE TITLE
Questions about paper

### ISSUE THREAD

**Issue by rzu512** [tdunning/t-digest#100]
At a quick glance, I can't quite find the rule for adding two centroids in line 9 of algorithm 1. Sorry if that is actually in the paper. According to the source code ([link](https://github.com/tdunning/t-digest/blob/01ea144ca865361be6786fd502bb554c75105e3c/core/src/main/java/com/tdunning/math/stats/Centroid.java#L79)), I assume the rule for adding centroid a and centroid b is:
```c
new_count = a.count + b.count;
new_centroid = (a.centroid * a.count + b.centroid * b.count) / (a.count + b.count)
```
Is that correct?

**Comment by tdunning** [comment]
Yes. I think that is correct.

Some implementations might keep a sum instead of a centroid, but this one
keeps the centroid.

For numerical stability, the update might be done using Welford's method,
but that is just a rearrangement of the operations you have. That is:


new_count = a.count + b.count;

if (a.count >> b.count) {

  new_centroid = a.centroid + b.count * (b.centroid - a.centroid) / new_count

} else if (a.count << b.count) {

  new_centroid = b.centroid + a.count * (a.centroid - b.centroid) / new_count

} else {

  new_centroid = (a.centroid * a.count + b.centroid * b.count) / new_count

}

This kind of code expansion is what tends to make it attractive to keep a
sum,count pair instead of a mean,count pair.
