### ISSUE TITLE
Questions about digest accuracy

### ISSUE THREAD

**Issue by magict4** [tdunning/t-digest#124]
Hi,

First, thank you for creating such a great library!

I am trying different `compression` values to see how they affect accuracy. I am using [ComparisonTest](https://github.com/tdunning/t-digest/blob/0820b016fefc1f66fe3b089cec9b4ba220da4ef1/quality/src/test/java/com/tdunning/tdigest/quality/ComparisonTest.java) as a reference to see how you measure accuracy. One thing I can't understand is why `e1` is large when `q` is small(0.00001, 0.0001, 0.001, 0.01, 0.1). 

Relevant code with my understanding
```
for (double q : quantiles) {
    // Let's say q is 0.1
    double x1 = dist.quantile(q); // x1 is p10(10% of total numbers are less than x1) based on TDigest algorithm.
    double e1 = Dist.cdf(x1, data) - q; // Dist.cdf(x1, data) returns actual percentile for x1. e1 represents the difference between actual percentile and expected percentile(0.1).
}
```

The following line is extracted from `sq-tree-comparison.csv`.

tag | compression | q | e1 | e2 | t.size | q.size
--- | ------------- | - | -- | -- | ------ | ------  
gamma | 20 | 0.1 | 0.16262 |-0.000125 |222 |18100

In above example, is actual percentile equal to 0.26262(0.1 + 0.16262)? Meaning actually there are 26% of total numbers are less than x1 while TDigest only reports 10%? If not, could you suggest some better ways to measure accuracy?

Thanks!

**Comment by tdunning** [comment]
The problem there is the Gamma(0.1, 0.1) distribution is violently skewed.
With compression=20, you only have about 10-12 centroids to play with and
the mean of the first non-trivial one is going to be wildly off.

Put it this way, even though the mean of that distribution is 1, here are
some quantiles:

> x = rgamma(1e6, 0.1, 0.1)

> mean(x)

[1] 0.9980511

> quantile(x, c(0.001, 0.01, 0.1, 0.5))

        0.1%           1%          10%          50%

8.396933e-30 7.849217e-20 6.312417e-10 5.970764e-03


I use that as a test distribution just because it is more evil than
anything I have run into in the real world.

I would have to look at the specifics of this case to determine what is
going on, but I expect that when you ask for quantile(0.1), you get a value
that is just a bit bigger than 6.3e-10. If that value is just 8.7e-6, then
the reverse quantile operation will give you q=0.26. Since the center of
that centroid is a mean and since means and medians are so screwy in this
distribution, this isn't an entirely surprising result.

**Comment by magict4** [comment]
Thank you Ted!

We plan to use TDigest to measure server response time. If Gamma(0.1, 0.1) is far from reality, do you have any recommended x, y values for Gamma(x, y) to model server response time? Smilier to [this graph](https://stats.stackexchange.com/a/46374). I guess response time distribution varies from service to service, but any recommended x, y values would help us to start.

**Comment by tdunning** [comment]
I am going to answer you in two parts. This part talks about how to
generate random numbers that look like an arbitrary latency spectrum.

So, if I want to match this sample with a random number generator:

[image: image.png]

I would use a mixture of log-normal distributions (this was hand-generated
by eyeballing):

0.4107 * LN(110000, 0.22)
0.5133 * LN(250000, 0.29)
0.0616 * LN(700000, 0.3)
0.0144 * LN(850000, 0.03)

I use LN to denote a log-normal distribution with a known MEAN and SPREAD.

In R, you can generate a sample of a log-normal distribution using
exp(rnorm(n, log(mean), spread))

In Java, I would write

Random gen = new Random();
AbstractContinousDistribution dist = new MixtureDistribution(
        Lists.newArrayList(0.4106776, 0.513347, 0.06160164, 0.01437372),
        Lists.newArrayList(new LogNormalDistribution(110000, 0.22, gen),
                new LogNormalDistribution(250000, 0.29, gen),
                new LogNormalDistribution(700000, 0.3, gen),
                new LogNormalDistribution(850000, 0.03, gen)),
        gen);


Where you have these definitions:


private static class MixtureDistribution extends AbstractContinousDistribution {
    private List<Double> weights;
    private List<? extends AbstractContinousDistribution> dists;
    private Random gen;
    private double total;

    MixtureDistribution(List<Double> weights, List<? extends
AbstractContinousDistribution> dists, Random gen) {
        this.weights = Lists.newArrayList(weights);
        this.dists = dists;
        this.gen = gen;
        total = 0;
        for (Double weight : weights) {
            total += weight;
        }
    }

    @Override
    public double nextDouble() {
        double u = gen.nextDouble() * total;
        for (int i = 0; i < weights.size(); i++) {
            if (u < weights.get(i)) {
                return dists.get(i).nextDouble();
            }
            u -= weights.get(i);
        }
        // could squeak through due to round-off
        return dists.get(weights.size()-1).nextDouble();
    }
}

private static class LogNormalDistribution extends
AbstractContinousDistribution {
    private final Normal base;

    LogNormalDistribution(double mean, double dispersion, Random gen) {
        this.base = new Normal(Math.log(mean), dispersion, gen);
    }


    @Override
    public double nextDouble() {
        return Math.exp(base.nextDouble());
    }
}

**Comment by tdunning** [comment]
Now ... for a second answer. About how to measure the distribution of
latencies (aka response times).

The fact is that if you *know* that your values will always be response
times and if you *know* that you are measuring these competently enough to
never have negative values or big zero-point shifts due to clock skew, then
you might be happier with LogHistogram from this same library.

The virtues of LogHistogram include:

1) all errors are relative in measurement space. That is, you get an error
guarantee as a percentage of your response time. This is easier to explain
some days.

2) faster. This almost never matters.

3) smaller. A little bit. Not usually be more than a factor of 2.

The defects are:

1) assumes that you want constant relative error in measurements for
positive values. If you don't absolutely know that you want that, t-digest
is the right answer.

**Comment by magict4** [comment]
I think I get all I need. Thank you!
