### ISSUE TITLE
How to update or increment previously inserted values?

### ISSUE THREAD

**Issue by pcallahan-r7** [tdunning/t-digest#142]
Let's say I'm tracking the value of items `0-n` in a t-digest.   As time goes on, the value for `item-i` increases.  I'd like to update the previous value in the t-digest to reflect the new state.  I don't think I can just add the new value for `item-i` because it will distort the data.   Is there a way to update or remove previous values?

Thank you

**Comment by tdunning** [comment]
I can't see a good way to do this because it would change our trade-offs of accuracy. There are some approaches that can allow samples to be removed, but these all lose accuracy. The most egregious problem occurs with the modification of the extreme values (because we maintain those exactly). If those move, we can't know the new extreme value.

I am going to close this as WONT_FIX
