### ISSUE TITLE
highly skewed data results in wrong percentile[need suggestion]

### ISSUE THREAD

**Issue by tannaga** [tdunning/t-digest#143]
In the below example, p50 computed by tdigest vs the regular formulae is significantly different. 
this is mimicking a scenario where typically my service latencies is between 240-250 ms and in worst case it is between 50-60 s.

```
245,246,247.249,240,243,248,250,241,244,245,245,247,243,242,241,50100,51246,52247.52249,51240,53243,59248,59250,57241,56244,55245,56245,575247,58243,51242,54241
```
tidest p50 --> ~25s
regular formulae p50 --> 0.25s

Is there any recommendation to handle such cases other than increasing the compression ratio?
Thank you in advance!!

**Comment by tdunning** [comment]
I am building a test case based on your data now.

I would not expect errors such as you are seeing.

**Comment by tdunning** [comment]
I don't understand the problem you are having. Here is a test case:
```java
    @Test
    public void testExplicitSkewedData() {
        double[] data = new double[]{
                245, 246, 247.249, 240, 243, 248, 250, 241, 244, 245, 245, 247, 243, 242, 241,
                50100, 51246, 52247, 52249, 51240, 53243, 59248, 59250, 57241, 56244, 55245,
                56245, 575247, 58243, 51242, 54241
        };

        TDigest digest = factory(50).create();
        for (double x :data) {
            digest.add(x);
        }

        assertEquals(Dist.quantile(0.5, data), digest.quantile(0.5), 0);
    }
```
This just adds the data you give and compares it to the actual median from the data. When I run this test it succeeds.

I will close this as Not-a-Bug, but if you have additional observations or see an error in my test, please re-open it.

In this case, since there are only 31 data points, they are all retained by the t-digest and the result is precisely correct (50100).
