### ISSUE TITLE
[DISCUSS] Is it possible to skip sorting inputs

### ISSUE THREAD

**Issue by cyb70289** [tdunning/t-digest#153]
Benchmark shows my C++ implementation costs 45ns amortized time in processing one data point on a five year old i7 machine, with `compression  = 100, input buffer size = 500`. Looks pretty good.
With profiling, I find most CPU time is in sorting the input buffer. So I'm thinking if it's possible to skip the sorting to improve performance (I tried with sorted input and observed boost up to 15ns per data point).

Here is an immature idea, would like to know if it's reasonable.
The basic idea is to convert an unsorted array into a t-digest directly.
- Pre-allocate input tdigest buffer with `size = compression/2`, cut it into #size bins and pre-calculate quantile limit of each bin.
- Find min and max values of the buffered input.
- Iterate input, for each value, calculate `quantile = (value - min) / (max - min)`, put it directly in according bin per quantile.
- After iteration, there may be some empty bins, and some oversized bins. Divide oversized bins into adjacent bins and fill/remove empty bins to keep the t-digest property. Use pre-calculated quantile limit to achieve this, don't evaluate scale functions.
- Merge this input t-digest with existing t-digest.

**Comment by tdunning** [comment]
Your speed sounds about right (and about the same as the java version).

And you are correct that the sort dominates the cost if the buffer is big
enough.

Your idea about converting an unsorted array has a few issues, I think. It
is nice to be able to do this, but I don't think you can do without any
sorting at all (although you can hide that to some degree).

But the real problem is in the line where you talk about calculating the
quantile. That isn't the quantile, or even a good approximation of it. That
means that the binning isn't going to work. Precomputing the scale function
works, but it doesn't save anything because computing the weight limit has
about the same cost.

So what you suggest is fine, but that step of computing the quantile of
each sample requires that you know the distribution, but to know the
distribution, you need a t-digest.  The natural solution is to sort a
tranche of data, convert to a t-digest and then sweep the remaining data
for data points that fit into existing centroids by the binning approach
you describe. If the data is randomly ordered, then a few passes through
the data will result in a t-digest on the entire data set.

But the cost here is a few passes through the data. Taking batches of size
b and then sorting them and merging with the t-digest is very nearly the
same cost.

I think that the highest quality t-digest could be constructed from a large
batch of data by taking modest-sized tranches and creating a t-digest from
each tranche. Then take all the resulting centroids as a new data batch and
sort them in batches in the same way. I believe that the first pass will
dominate the overall costs which would mean that the second pass could be a
complete sort and merge step.

**Comment by cyb70289** [comment]
Thanks @tdunning !

**Comment by tdunning** [comment]
I just wanted to say ...

Your question together with two other issues got me to looking more carefully at what happens with repeated values and I actually found a significant bug as a result. Commit coming shortly.

Good questions are sometimes almost as good as good answers!

Thanks!

**Comment by cyb70289** [comment]
Glad to hear that.
I've uploaded PR to apache arrow community. Would you mind having a look? Thanks.
https://github.com/apache/arrow/pull/9310

**Comment by tdunning** [comment]
So I just read through your implementation and I see that you are using the standard sort. 

My question as a C++ naive person is how does that sort know the collation order?

The issue here is that if the sort is unstable (like a quick sort) you really need to order by mean and weight. But the ordering on weight depends on whether the centroid is before or after the median (which depends on how the data is sorted!). If you don't do this well, repeated data values can give severely degraded accuracy and can violate the t-digest invariants.

The way I handle this in my upcoming patch to the Java implementation is to sort on mean, weight ascending. Then I make another pass through the data handling each run of centroids with the same value specially according to whether it is before, after or straddling the median. I have considered switching to a stable sort by re-implementing the sort would be a frustrating and potentially error-prone exercise at this point.

Your situation might be better if your sort is stable. If so, then we should talk through the situation and think about a test case to validate that stability alone is a good enough guarantee.

**Comment by cyb70289** [comment]
Thanks @tdunning , C++ sort can accept a customized comparison function. Pairs of data points are passed to that function to compare and return the order. By default, a naive lessthan function is called, which sorts the array in ascending order.
I'm using `std::sort` which is unstable, `std::stable_sort` is stable.

For where I called `std::sort`, I'm sorting the inputs only (without weights, as weight=1 for all inputs). Then use a merge sort approach to find next minimal mean from current tdigest buffer and input. I didn't combine and sort the input and current tdigest buffer together.

For the `toward median` approach, do you have test case to experience the issue?

**Comment by tdunning** [comment]
Your approach sounds like it should be fine. I avoided the merge step
because it seemed I would have a shift even if I did the merge step. I
could have done a ping pong buffer or doubled the size of the digest buffer
and shifted before merging, but I finally decided the copy and sort
together was simpler. Obviously this wasn't quite as good in retrospect as
I thought.

I just committed some tests that illustrate the problem (if you have it).
See ReproTest where I use this loop to generate data with lots of
duplicates:

```java
double[] data = new double[10000];
for (int i = 0; i < data.length; i++) {
    // these samples are truncated and thus have lots of duplicates
    // this can wreak havoc with the t-digest invariants
    data[i] = Math.floor(gen.nextDouble() * 10);
}
```
This creates some large and some small centroids near the ends of the
digest. If your sort reorders these, you have trouble. Since you don't sort
the centroids that are already in the digest, I think you should be safe.
As you point out, the ordering of the new data doesn't matter as long as it
is merged cleanly with the existing data.

I will be doing accuracy tests shortly. That will determine whether it is
important to do merging in alternate directions. My suspicion is that the
alternating was only helpful in covering the problems with the unstable
sort.
