### ISSUE TITLE
Silly question: Why is it called t-digest?

### ISSUE THREAD

**Issue by yurivish** [tdunning/t-digest#158]
Hi Ted, as I'm learning more about the t-digest and reading your excellent paper about it I began to ponder the origins of the name. 

According to the [original q-digest paper](https://arxiv.org/pdf/cs/0408039.pdf), the Q stands for Quantile. Is the T in t-digest a similar shorthand for a technical term, or it a (perfectly justified) eponym? :-)

Filing this as an issue since this might benefit from a mention in the readme.

**Comment by tdunning** [comment]
The truth is that it is just a bit too embarrassing to put into the README.

I was working on k-means clustering. And dp-means clustering. And I saw the
q-digest. And I had a digest that needed a name.

So it seemed natural to pick a letter.

A letter to precede a word that starts with D.

So, yeah, it is kind of a cryptic eponym. And it probably never would have
happened if I had thought of the algorithm as a sketch instead of a digest.

At least it turned out to be a name that people seem to retain well. And
there weren't any accidental collisions with some other algorithm. So, in
the end, it turns out to be not such a bad name.
