### ISSUE TITLE
Substract a t-digest

### ISSUE THREAD

**Issue by papapon** [tdunning/t-digest#159]
I use the python version ot the t-digest to compute percentiles on a stream of data. At each minute I create a t-digest in which I add the data relative to the minute. I sum the 15 last t-digest to get my percentiles over the last 15 minutes. For this, I use an array of the last 15 t-digests. I update this array over time. But it is very consuming, because I keep an array for each period (15 minutes, 1 hour, ...). The longer the period is and the more I have to add the minutes t-digest. 

So, I would like to know if it is possible to subtract a t-digest. This would allow me to keep a t-digest of a period to add the new one and subtract the older one.

**Comment by tdunning** [comment]
The first response here needs to be that I don't maintain the python version (I think that there may be more than one). So if this discussion comes down to required changes, I can't make them.

On the other hand, your question is pretty general, and I am happy to answer that.

- the most specific part of your question asks about whether t-digests can be subtracted. The answer is that they can kind-of-sort-of be subtracted, but you lose any of the guarantees so it is a really bad thing to do.

- the more general part of your question has to do with strategies for keeping t-digests that maintain both accuracy and time resolution while also allowing quick merging at query time.

This is a bigger question and there is no single answer. Some things stand out. First, merging digests should be pretty fast so it should be practical to merge a fairly large number of digests at query time. For instance, it is reasonable to require several hundred data points for a plot and, for raw speed, each of these data points could be composed from hundreds or thousands of digests without the overall speed of the rendering to be horrible. My own feeling that rolling up roughly at 100:1 isn't a bad idea. Thus minute -> hour -> day -> month is a viable rollup schedule that allows you query at 1 minute resolution over almost any time period you need even if you need to have a result with hundreds of data points.

Another part of your question has to do with the merging strategy. Most people collect at a tight time frame and then periodically use an offline process to create the rollups. Given that there aren't all that many minutes in the last day, you can often defer the rollup until the end of the day. Most importantly, these rollups don't need to be created in your data acquisition chain. At low-ish data volumes, you can view the creation of even the minute-wise digests as rollups that shouldn't be in the main collection path.

Even the idea that hourly and daily rollups have to be created from the shorter time digests is not necessarily a given. It is reasonable to have, say, three live digests to which you feed samples as they arrive, one for each live time period. This avoids the rollup processing entirely. I tend to think that the rollup idea is better, but you can have a middle ground as well where you roll up minutes into hours but then create the daily directly from the minutes as well. This makes sense if you are rolling up at the end of the day, but it can even be nice to do when you create the monthly rollup.

And finally, let me say that I am happy to help talk to the maintainers of the Python library you are using if their merge times are slower than they should be. I will need a lot more specifics if you want to do that, however.

Does this answer your question?

**Comment by papapon** [comment]
Thank you very much for your time and your complete answer. 

It is clear to me that you do not maintain the python version. I have posted here because it is a general question about the structure of the t-digest and its possibilities. 

I understand that it is therefore not possible to subtract from the t-digest without loss of precision, it would have helped me a lot. 

The strategy I am currently using is working but is starting to show signs of weakness. Indeed the number of timeseries on which I calculate these tdigests becomes important (more or less 250). The calculation for several periods becomes problematic beyond 1 hour because I don't have an infinite computing power (just a laptop). 
All these calculations are done in real time, because I need two percentiles (for example 20 and 80) in real time. If the values I store in the tdigest every minute exceed the value associated with the two percentiles then I raise an alert. This alert is what I am looking for in real time. 

I have also thought about the solution you propose to create several tdigests in parallel: one for the minute, one for the hour and one for the day. This solution allows me to calculate the percentiles more easily over long periods. However, it makes my calculations more complex, for example to have the last three hours. It is 5:08 pm in France, so I have to take the 5pm (8 minutes) tdigest + the 3pm and 4pm (120 minutes) tdigest + the 52 other tdigests between 2:08 and 3pm.  I can trick by taking the whole 14h and have not the last 3 hours but the 3 hours and 8 minutes, but the more I advance in the hour the more it skews. So not so good idea in my case.

I asked my question here because I thought that even if it wasn't possible to do the percentile math from the t-digest it might be possible to use another structure. I saw in your paper that there are, for example, q-digest. You must surely know others to solve my problem, the size of the digest is not the biggest criterion in my case.

**Comment by tdunning** [comment]
OK. This is a common use case.

To summarize, you want to create a longer term t-digest to find anomalous values (relative to the long-term pattern) to create alerts. It is likely that you want to test every sample as it arrives and you don't want to keep recreating 3 hour (or whatever) reference digests for every sample. I expect that you want flexibility in terms of the length of the reference digest and you want to have the reference be "pretty close" to the current time.

My normal recommendation here is that you have an abstract query function to which you give a time range. That query function looks at the digests that are in your persistent store and combines them to get a composite digest. Ideally, that query function would also write back accumulated for, say, hours in order to speed up later queries. In a really fancy version there would be a policy about the time-to-live for these accumulated digests so that the digest for the 4.5 hours ending at 3:47 would only live for, say, 5 minutes, but the hourly summary ending at 3:00 would live a long time.

If you have such a query function and your anomaly detection function uses minute aligned windows then when the first sample of a new minute arrives, the query function would compute and cache the history digest for that new minute. The second sample would simply use that cached value so only the first sample would pay the merge price.

Furthermore, if you are using, say, 4.5 hour window and your query function has a policy that time periods are broken down into big and small interfaces, then the first sample that arrives when the cache is clean would cause several hourly cached values to be computed. At the beginning of the next even hour, the first sample arriving (say at 6:00:04) the query for 4.5 hours would be decomposed into hourly time ranges [2:00 - 3:00), [3:00 - 4:00), [4:00 - 5:00), [5:00 - 6:00), plus the minutes starting from 1:30 to 1:59. The cache would have values for 4 of the hourly values, but not for [5:00 - 6:00) so that would be computed from the minutes and cached. The query would require the merger of 30 minutes + 3 hours + 60 minutes for the first sample and the second sample would get a cached value for [1:30 - 6:00). At 6:01, we would compute the digest for [1:31 - 6:01) as the merger of 29 minutes + 4 hours + 1 minute. That value would be cached. If you get 1000 samples per minute spread across 250 different time series, you would get 750 cache hits per minute and would require 250 mergers with an average of 34 digests which should take milliseconds at most (microseconds in Java). If you use an even four hour window in your query, the merge size would range from 5 digests to 62 digests depending on which minute in the hour you have. Asking for previous 7 days would have comparable size because of the caching of daily and hourly values.

From your applications point of view, the application simply asks for a digest for a time range and gets a quick answers. There would be (very small) cost at the beginning of each minute and hour to generate new aggregates.

Does this meet your needs?

**Comment by papapon** [comment]
Thank you very much. 

I'll try your proposal.

**Comment by tdunning** [comment]
Cool.

I will close this issue now but you can open a new one any time (or even re-open this one if needed).
