### ISSUE TITLE
Is cdf(x) = q less accurate than quantile(q) = x ?

### ISSUE THREAD

**Issue by jaystarshot** [tdunning/t-digest#168]
Section 2.9 of the [paper](https://github.com/tdunning/t-digest/blob/main/docs/t-digest-paper/histo.pdf) mentions that 

> The information in a fully-merged t-digest is not sufficient, in general to precisely determine the empirical quantile q of any particular x

Also there are no empirical assessments of this case

**Comment by tdunning** [comment]
I am not sure what empirical assessments that you want. The t-digest loses information. That is what a sketch does. 

Thus, there is not enough information to recover either exact quantiles or the CDF. The goal is to get as precise an estimate as possible.

Also, although cdf and quantile are often thought of as inverses of each other, the quantile function cannot actually be precisely inverted because it is many to one at the discontinuities in the CDF.

The test cases have a fair bit of testing for both `cdf()` and `quantile()`. Is that what you are looking for?

**Comment by jaystarshot** [comment]
After reading that line in the paper, i was of the impression that cdf(x) is less accurate than quantile(q) , but now its clear to me that this statement was in general for all sketches.

Like in Figure 6
There is a graph for absolute error vs q 
Where absolute error is from quantile estimates of t digest vs actual quantile values


It would be great to have a graph for 
Absolute error vs q
Where absolute error is from cdf of points from t digest vs actual cdf 

Also I had a silly question but the complexity of both (cdf() and quantile()) is not mentioned in the paper or the comments, can we add a comment there?

**Comment by tdunning** [comment]
Point taken on the cdf error graph. I have done that for my own reference so it doesn't hurt to document it (except for journal papers with a page limit, of course).

Regarding complexity, do you mean computational complexity? If so, both have O(\delta) complexity. For any given sketch, that is a constant. That could be decreased if we wanted to put a bit of an index in front of the digest, but nobody cares yet.

**Comment by jaystarshot** [comment]
Thank you for the clarification !
