### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by Sunny-Island** [tdunning/t-digest#170]
When I run `mvn install `or `mvn test`, build failure happened.
`
[ERROR] Failed to execute goal on project t-digest-benchmark: Could not resolve dependencies for project com.tdunning:t-digest-benchmark:jar:3.4-SNAPSHOT: Could not find artifact com.tdunning:t-digest:jar:3.3-SNAPSHOT -> [Help 1]
`
It seems that no 3.3 or higher version in remote repo? https://mvnrepository.com/artifact/com.tdunning/t-digest

**Comment by Sunny-Island** [comment]
maven: 3.8.1
java: 1.8.0_291
os: Mac OS 10.15.7 (19H1030)

**Comment by tdunning** [comment]
This may have to do with my fidgeting with the repo as part of releasing 3.3. What happens during the release process (as I did it) is that parts of the code get updated to talk about 3.4-SNAPSHOT, but the parent pom doesn't get updated. Once the release was completed, I manually updated the poms to repair this. You may have updated your copy of the sources in the moments when I had it in a defective state.

Sadly, this process appears to be an inevitable part of the maven release process. In the future, I will investigate conducting the release process from a branch instead of trunk.

I just did a quick partial test by pulling the latest sources and starting a test. This problem did not appear.

Can you pull the source code again and re-test? I expect it will work.

**Comment by Sunny-Island** [comment]
Thank you for your reply!
I pull it again but it doesn't work. Could you give more suggestions?

**Comment by tdunning** [comment]
OK. That is very strange. I am retesting my self with a fresh clone.

Next step is the traditional questions:

1) can you describe your platform?  My platforms are OSX and Ubuntu.

2) can you inspect the pom.xml files manually and look at the <parent> ... </parent> sections?  Please tell me what versions they refer to.

3) can you upload and share the output of `mvn test`?

**Comment by Sunny-Island** [comment]
```
[ERROR] Failed to execute goal on project t-digest-benchmark: Could not resolve dependencies for project com.tdunning:t-digest-benchmark:jar:3.4-SNAPSHOT: Could not find artifact com.tdunning:t-digest:jar:3.3-SNAPSHOT -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :t-digest-benchmark
```

My platform: 
MacOS
JAVA 1.8.0_291
MAVEN 3.8.1

**Comment by tdunning** [comment]
Got it!

I understand what happened here and replicated it by blowing away my .m2 directory. I had been looking for the reverse problem.

Will fix this instantly and cut a new release.

THANK YOU!!!

**Comment by tdunning** [comment]
Actually, this only affects development. No new release needed.

I have tested the change and will push in 30 seconds.

**Comment by Sunny-Island** [comment]
Done! Thank you!
