### ISSUE TITLE
Mergeability of t-digest 

### ISSUE THREAD

**Issue by patelprateek** [tdunning/t-digest#177]
I have question regarding merge-ability of t-digest. Is it one-way mergeable or fully mergeable ?
reason i asked is in this paper  : http://www.vldb.org/pvldb/vol12/p2195-masson.pdf , they mentioned t-digest to be one-way mergeable
```
The problems of having high relative errors on the larger quantiles has been addressed by a line of work that still uses rank error,
but promises lower rank error on the quantiles further away from the
median by biasing the data it keeps towards the higher (and lower)
quantiles [7], [8], [17]. The latter, dubbed t-digest, is notable as
it is one of the quantile sketch implementations used by Elasticsearch [18]. These sketches have much better accuracy (in rank)
than uniform-rank-error sketches on percentiles like the p99.9, but
they still have high relative error on heavy-tailed data sets. Like GK
they are only one-way mergeable
```

Thanks

**Comment by tdunning** [comment]
That paper is not clear about what they mean by "fully mergeable". They
seem to think that it means that digests can be merged in a distributed
fashion. Jeff Phillips paper
<https://www.cs.utah.edu/~jeffp/papers/mergeSumm-MASSIVE11.pdf> has a
better definition where digests are fully mergeable if they can be merged
while retaining the same accuracy and size constraints as the original
digests.

The second definition implies something kind of like the first in that you
can construct a fully mergeable digest by separately creating digests for
parts of the data and then merging them.

The t-digest is fully mergeable in the sense of Phillips. I don't know what
Masson, Rim and Lee are talking about, really.

**Comment by patelprateek** [comment]
@tdunning : thanks for the reply. 
I do use t-digest in some of the map-reduce pipelines and got curious after reading that paper if I am missing some essential caveats . thanks for clarification

**Comment by tdunning** [comment]
The essential caveats are:

- the t-digest has (mostly) fixed memory size. That means that it cannot
maintain full relative accuracy for some distributions. Mostly this doesn't
matter.

- the t-digest has better properties if it can stay in memory because it
buffers incoming data before adding it to the digest. When you serialize a
digest it is forced to fully merge and compress.

- it is often true that the worst errors will occur just as the digest
starts to combine samples. For small sample count, all samples are retained
and thus error is zero. When you get centroids with two samples,
interpolation can give errors corresponding to 0.5/N in q and equal to the
separation between the samples in measurement space. These errors are
typically much worse than what you get with larger sample counts and are
thus a bit surprising.

Beyond these, you should have very few problems.
