### ISSUE TITLE
Behavior when compression ratio is 1

### ISSUE THREAD

**Issue by mqliang** [tdunning/t-digest#193]
Hey, If set  compression ratio as 1 when create the t-digest, does it means "no compression"?

**Comment by tdunning** [comment]
No.

And it is hard to make sense of the compression factor in that way since
the digest is finitely bounded in size for an arbitrary amount of input
data.

The compression factor is better interpreted as the desired size bound for
the digest when you write it to disk. The amount kept in memory will be a
factor larger than this in order to maximize accuracy during creation of
the sketch.
