### ISSUE TITLE
Allow arbitrary scaling laws for centroid sizes

### ISSUE THREAD

**Issue by oertl** [tdunning/t-digest#37]
As discussed in #30 it makes sense to allow other scaling laws for centroid sizes than `4*q*(1-q)`. For example, `2*sqrt(q*(1-q))` could be useful if the underlying distribution needs to be estimated. Sometimes only one-sided extreme quantiles are interesting. For example, in case of response times, where slow values (quantiles close to 100%) are more interesting, it could make sense to have a scaling law like `(q<0.5)?1.:4.*q*(1-q)`.

**Comment by tdunning** [comment]
I have been noodling on this a bit in conjunction with your "Improved bounds" comments and I understand now why the root limit provides such good access.

The simplest error bound is proportional to the count for each centroid.  This is the rationale of the original bound. 

The measured accuracy for the t-digest in practical tests is much better than this due to the use of interpolation.  If we assume the ideal case that the contents of each centroid are uniformly distributed between the mid-points to the adjacent centroids, then linear interpolation between these points should give us a piece-wise linear approximation of the empirical CDF.  The error of this approximation is obviously second-order in the centroid count, not linear.  This means that the root limit on centroid size should actually give the desired constant relative accuracy in q near the extremes and the original size limit should give us over-kill.

The real benefit, is that the root limit gives not only an asymptotic bound on the number of required centroids, but also gives a substantially smaller number of centroids in practice as reasonable numbers of data points.  At 10^6 data points with $1/\delta = 50$, the standard limit gives 321 centroids (best case) and the root limit gives less than 80 for a 4:1 savings.  With 100 samples, the two approaches give the same number of centroids.

**Comment by tdunning** [comment]
I have been noodling on this a bit in conjunction with your "Improved bounds" comments and I understand now why the root limit provides such good access.

The simplest error bound is proportional to the count for each centroid. This is the rationale of the original bound.

The measured accuracy for the t-digest in practical tests is much better than this due to the use of interpolation. If we assume the ideal case that the contents of each centroid are uniformly distributed between the mid-points to the adjacent centroids, then linear interpolation between these points should give us a piece-wise linear approximation of the empirical CDF. The error of this approximation is obviously second-order in the centroid count, not linear. This means that the root limit on centroid size should actually give the desired constant relative accuracy in q near the extremes and the original size limit should give us over-kill.

The real benefit, is that the root limit gives not only an asymptotic bound on the number of required centroids, but also gives a substantially smaller number of centroids in practice as reasonable numbers of data points. At 10^6 data points with $1/\delta = 50$, the standard limit gives 321 centroids (best case) and the root limit gives less than 80 for a 4:1 savings. With 100 samples, the two approaches give the same number of centroids.

**Comment by tdunning** [comment]
I am closing this since all the recent implementations use the root limit. This root limit gives a fixed and well understood bound on size of the digest as well as providing good empirical error bounds.

There has been no serious demand for alternative limits.
